language: shell

services:
  - docker

install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  - echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  - sudo apt-get -qq update
  - sudo apt-get install -y shunit2
  - sudo apt-get install -y mongodb-org-shell
  - docker build . -t martel/mongo-replica-ctrl:travis
  - docker swarm init
  - docker stack deploy -c test/docker-compose.yml mongo

script:
  - sh test/ci-test-running-basic.sh
  - sh test/ci-test-scale-basic.sh
